services:
  # 1. El Backend (Tu c√≥digo Rust)
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      # OJO: En Docker, el host no es 'localhost', es el nombre del servicio ('db')
      - DATABASE_URL=postgres://ctv_user:ctv_password@db:5432/ctv_news
      - PORT=3000
      - RUST_LOG=info
      - JWT_SECRET=cambiar_esto_por_secreto_seguro_en_produccion
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    restart: always

  # 2. La Base de Datos
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432" # Exponemos puerto por si quieres conectarte con tu cliente SQL local
    environment:
      - POSTGRES_USER=ctv_user
      - POSTGRES_PASSWORD=ctv_password
      - POSTGRES_DB=ctv_news
    volumes:
      - pg_data:/var/lib/postgresql/data
      # Opcional: Copiar tu init.sql para que se cree la estructura al iniciar de cero
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg_data: